CREATE TABLE IF NOT EXISTS noticias (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fecha TEXT NOT NULL,
  titulo TEXT NOT NULL,
  lugar TEXT NOT NULL,
  contenido TEXT NOT NULL,
  imagen TEXT NOT NULL DEFAULT '',
  imagen_alt TEXT NOT NULL DEFAULT '',
  publicada INTEGER NOT NULL DEFAULT 1 CHECK (publicada IN (0, 1)),
  creado_en TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
